#!/usr/bin/env python3
"""Regenerate requirements-dev.lock from the pinned upstream images' own locks.

The test environment exists to import the code that runs inside the released agent and mcp
images, so its versions must come from those images rather than from whatever PyPI published
most recently. Resolving `requirements-dev.in` freely is what let 80 of 168 shared packages
drift ahead of the containers -- `langchain-core` by two minors, while `concierge/` imports its
message and chat-model classes directly.

Usage (after `demo.py bootstrap`, which creates the pinned checkout this reads):

    .venv/bin/python scripts/relock-dev.py

The three images do not agree with each other -- agent and mcp differ on ten packages, and
chatbot is a whole OpenTelemetry minor behind both -- so no single virtualenv can mirror all
three. The constraint set is therefore layered, most authoritative first:

    agent  >  mcp  >  chatbot

The agent image wins because it is the runtime the tests actually assert about: the LangGraph
tool loop, `concierge/telemetry.py`, and every span the Langfuse half of the demo checks. mcp
fills in nothing today but would cover a package the agent image drops. chatbot contributes
only what neither of the others has -- in practice gradio's own stack -- which is why the Gradio
debug client can be imported locally at the version its image ships.

The packages where the winning pin differs from another image's are printed at the end. They
are not fixable here; they are the cost of one venv over three, and the report is so that a
test which turns out to depend on one of them can be recognised rather than puzzled over.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from launcher import core  # noqa: E402

IN_FILE = ROOT / "requirements-dev.in"
LOCK_FILE = ROOT / "requirements-dev.lock"
CONSTRAINTS = core.RUNTIME / "image-constraints.txt"
UPSTREAM = ROOT / ".upstream/opentelemetry-demo/src"

# Most authoritative first. See the module docstring for why the agent image leads.
IMAGES = ("agent", "mcp", "chatbot")

PIN = re.compile(r"^([A-Za-z0-9_.\-]+)==([^\s;]+)$")


def normalise(name):
    """PEP 503 comparison form, so `langchain_openai` and `langchain-openai` are one package."""
    return re.sub(r"[-_.]+", "-", name).lower()


def read_pins(path):
    r"""The `name==version` pins of a requirements file, ignoring hashes and continuations.

    Upstream's locks are hash-pinned, with every entry a `\`-continued line followed by
    indented `--hash=` lines. Stripping the continuation and matching only bare pins leaves
    exactly the versions, which is all a constraints file may carry.
    """
    pins = {}
    for line in path.read_text().splitlines():
        candidate = line.strip().rstrip("\\").strip()
        match = PIN.match(candidate)
        if match:
            pins[normalise(match.group(1))] = match.group(2)
    return pins


def layered_constraints():
    """One pin per package, taken from the first image in IMAGES that names it.

    Returns the merged mapping and, for the report, every package whose winning pin disagrees
    with a lower-precedence image's.
    """
    locks = {}
    for image in IMAGES:
        path = UPSTREAM / image / "requirements.txt"
        if not path.is_file():
            core.die(
                f"{path} is missing: run `demo.py bootstrap` first, which checks out the "
                "pinned upstream tree this derives from"
            )
        locks[image] = read_pins(path)

    merged = {}
    source = {}
    for image in IMAGES:
        for name, version in locks[image].items():
            if name not in merged:
                merged[name] = version
                source[name] = image

    overridden = [
        (name, source[name], merged[name], image, locks[image][name])
        for image in IMAGES
        for name in sorted(locks[image])
        if name in merged and source[name] != image and locks[image][name] != merged[name]
    ]
    return merged, overridden


def write_constraints(merged):
    """The exact-pin constraints file the compile below resolves against."""
    CONSTRAINTS.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by scripts/relock-dev.py from the pinned upstream images' locks.\n"
        f"# Precedence: {' > '.join(IMAGES)}. Do not edit; not committed.\n"
    )
    body = "".join(f"{name}=={version}\n" for name, version in sorted(merged.items()))
    CONSTRAINTS.write_text(header + body)
    core.log(f"wrote {len(merged)} image pins to {CONSTRAINTS.relative_to(ROOT)}")


def compile_lock():
    """`uv pip compile` the committed .in against the image constraints.

    --no-annotate/--no-header keep the lock a bare pin list, which is the format it has had
    since it was first written and the only format whose diffs are readable.

    --upgrade is what makes the two halves of the .in behave differently, and it is safe only
    because of the constraints. Without it `uv pip compile` re-uses whatever the existing lock
    already pinned, which would freeze the test-only tools at the version they happened to
    have. With it, every resolution is fresh: the constrained packages cannot move anywhere (an
    exact `==` leaves them nowhere to go), and pytest, pytest-asyncio and ruff -- the only
    packages no image pins -- land on their current releases.
    """
    core.need("uv")
    core.log("uv pip compile requirements-dev.in against the image constraints")
    result = core.run(
        "uv",
        "pip",
        "compile",
        IN_FILE,
        "--constraint",
        CONSTRAINTS,
        "--output-file",
        LOCK_FILE,
        "--python-version",
        "3.14",
        "--upgrade",
        "--no-annotate",
        "--no-header",
        "--quiet",
        check=False,
        cwd=ROOT,
    )
    if result.returncode:
        core.die(f"uv pip compile failed (exit {result.returncode})")


def report(merged, overridden):
    """What the new lock mirrors, what it does not, and what no single venv could."""
    pins = read_pins(LOCK_FILE)
    drifted = sorted(
        (name, merged[name], pins[name])
        for name in pins
        if name in merged and pins[name] != merged[name]
    )
    mirrored = sum(1 for name in pins if name in merged and pins[name] == merged[name])

    print(f"\n{LOCK_FILE.name}: {len(pins)} packages")
    print(f"  mirror an image pin exactly: {mirrored}")
    print(f"  test-only (no image pins it): {len(pins) - mirrored - len(drifted)}")
    print(f"  drifted from the image pin:  {len(drifted)}")
    for name, want, got in drifted:
        print(f"    {name:<44}image {want:<16}lock {got}")

    if overridden:
        print(f"\nnot mirrorable in one venv ({len(overridden)}): the winning image's pin differs")
        for name, won_by, version, lost_by, other in overridden:
            print(f"  {name:<40}{won_by} {version:<14}(vs {lost_by} {other})")

    return drifted


def main():
    if not IN_FILE.is_file():
        core.die(f"{IN_FILE} is missing: it is the committed source of the lock")

    merged, overridden = layered_constraints()
    write_constraints(merged)
    compile_lock()
    if report(merged, overridden):
        core.die("the lock does not mirror the image pins; the constraints were not applied")


if __name__ == "__main__":
    main()
